version: '3'
services:
  dbos:
    image: mysql:5.7
    volumes: 
         - my:/var/lib/mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: rootpass
       MYSQL_USER: abhi                                                
       MYSQL_PASSWORD: redhat
       MYSQL_DATABASE: mydb
  wpos:  
   image: wordpress:5.1.1-php7.3-apache
   restart: always
   depends_on: 
          - dbos
   volumes: 
        - wp:/var/www/html
   ports: 
        - 8081:80
   environment:
     WORDPRESS_DB_HOST: dbos 
     WORDPRESS_DB_USER: abhi
     WORDPRESS_DB_PASSWORD: redhat
     WORDPRESS_DB_NAME: mydb

volumes:
     my:
     wp: